// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDCtfJRGSzBJBEChd9jgdnyetlw175ALtM',
    appId: '1:496371983416:web:5861818425a602ad2f72cd',
    messagingSenderId: '496371983416',
    projectId: 'fact-flash',
    authDomain: 'fact-flash.firebaseapp.com',
    storageBucket: 'fact-flash.firebasestorage.app',
    measurementId: 'G-M76Y63395N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcczsupzXRrQIi8M0zUo7LTiN3pD03IU8',
    appId: '1:496371983416:android:817a818076f596fc2f72cd',
    messagingSenderId: '496371983416',
    projectId: 'fact-flash',
    storageBucket: 'fact-flash.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: 'YOUR_IOS_APP_ID',
    messagingSenderId: '496371983416',
    projectId: 'fact-flash',
    iosBundleId: 'com.example.factFlash',
    storageBucket: 'fact-flash.firebasestorage.app',
  );
}
